name: "Bug report"
description: "Create a generic bug report."
title: "bug: BUG TITLE"
labels: ["0.kind: bug"]
body:
  - type: "markdown"
    attributes:
      value: |
        Welcome to Nix Pelican. Please replace the **`bug: BUG TITLE`** template above with a short title summarising what the bug entails.

         ---
  - type: "dropdown"
    id: "version"
    attributes:
      label: "Package"
      description: |
        What package is affected by the issue?
      options:
        - "Please select a package."
        - "- Panel & Wings"
        - "- Peanel"
        - "- Wings"
      default: 0
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the bug"
      description: "Please include a clear and concise description of what the issue is."
    validations:
      required: true
  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Please include a step-by-step guide for reproducing this issue. Consider writing in concise, numbered bullet points to ensure that a developer can retrace your steps."
    validations:
      required: true
  - type: "input"
    id: "expected-behaviour"
    attributes:
      label: "Expected behaviour"
      description: "Please write a concise description of what was supposed to happen."
    validations:
      required: true
  - type: "textarea"
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: |
        If applicable, add screenshots to help explain your problem.
        If you need help uploading images to GitHub, please review the [relevant documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#uploading-assets).
    validations:
      required: false
  - type: "textarea"
    id: "logs"
    attributes:
      label: "Relevant log output"
      description: |
        If applicable, copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: "console"
    validations:
      required: false
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I assert that this issue is relevant for Nix Pelican"
      description: |
        This bug tracker is for actionable issues that are not the result of user error. If you need help using your system and are unsure if this is a bug with Nix Pelican.
      options:
        - label: "I assert that this is a bug and not a support request."
          required: true
        - label: "I assert that that I have read the [troubleshooting](https://github.com/Hythera/nix-pelican?tab=readme-ov-file#troubleshooting) section."
          required: true
        - label: "I assert that this is not a [duplicate of an existing issue](https://github.com/Hythera/nix-pelican/issues?q=is%3Aissue%20label%3A%220.kind%3A%20bug%22). "
          required: true
  - type: "markdown"
    attributes:
      value: |
        # Thank you for helping improve Nix Pelican!

        ---
